baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'



[module]
  [[module.mounts]]
    source = "./node_modules/alpinejs/src/index.js"
    target = "./assets/js/alpinejs"
